import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import {Button, Grid, GridItem, Show} from "@chakra-ui/react";



export default function Home() {
  return (
    <>
      <Head>
        <title>Game Hub App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
       <Grid templateAreas={
           {
               base:`"nav" "main"`,
               lg: `"nav nav" "aside main"`
           }
       }>
          <GridItem area='nav' bg='coral' >Nav</GridItem>
           <Show above='lg'>
               <GridItem area='aside' bg='gold'>Aside</GridItem>
           </Show>
          <GridItem area='main' bg='dodgerblue'>Main</GridItem>
       </Grid>
      </main>
    </>
  )
}
