import Head from 'next/head'
import {Grid, GridItem, Show} from "@chakra-ui/react";
import NavBar from "@/components/NavBar";
import GameGrid from "@/components/GameGrid";
import GenreList from '@/components/GenreList'
import {useState} from "react";
import {Genre} from "@/hooks/useGenres";


export default function Home() {
    const [selectedGenre, setSelectedGenre] = useState<Genre | null>(null)
    return (
        <>
            <Head>
                <title>Game Hub App {selectedGenre?.name}</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <Grid templateAreas={
                    {
                        base: `"nav" "main"`,
                        lg: `"nav nav" "aside main"`
                    }
                }
                      templateColumns={
                          {
                              base: '1fr',
                              lg: '200px 1fr'
                          }
                      }
                >
                    <GridItem area='nav'>
                        <NavBar/>
                    </GridItem>
                    <Show above='lg'>
                        <GridItem area='aside' paddingX={5}>
                            <GenreList onSelectGenre={(genre)=>setSelectedGenre(genre)}/>
                        </GridItem>
                    </Show>
                    <GridItem area='main'>
                        <GameGrid selectedGenre={selectedGenre}/>
                    </GridItem>
                </Grid>
            </main>
        </>
    )
}
